//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAholics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SportAholicsEntities : DbContext
    {
        public SportAholicsEntities()
            : base("name=SportAholicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NonRegisterEmail> NonRegisterEmails { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<PlayerPreference> PlayerPreferences { get; set; }
    
        public virtual ObjectResult<GetPlayerPerfernce_Result> GetPlayerPerfernce()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPlayerPerfernce_Result>("GetPlayerPerfernce");
        }
    
        public virtual ObjectResult<PlayerJoined_Result> PlayerJoined(string entryUser, Nullable<int> eventID)
        {
            var entryUserParameter = entryUser != null ?
                new ObjectParameter("EntryUser", entryUser) :
                new ObjectParameter("EntryUser", typeof(string));
    
            var eventIDParameter = eventID.HasValue ?
                new ObjectParameter("EventID", eventID) :
                new ObjectParameter("EventID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PlayerJoined_Result>("PlayerJoined", entryUserParameter, eventIDParameter);
        }
    
        public virtual ObjectResult<GetJoinedList_Result> GetJoinedList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJoinedList_Result>("GetJoinedList");
        }
    
        public virtual ObjectResult<JoinEvent_Result> JoinEvent(Nullable<int> playerid)
        {
            var playeridParameter = playerid.HasValue ?
                new ObjectParameter("playerid", playerid) :
                new ObjectParameter("playerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinEvent_Result>("JoinEvent", playeridParameter);
        }
    
        public virtual ObjectResult<GetUserList_Result> GetUserList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserList_Result>("GetUserList");
        }
    }
}
