//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAholics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.NonRegisterEmails = new HashSet<NonRegisterEmail>();
            this.Players = new HashSet<Player>();
        }
    
        public int EventID { get; set; }
        public Nullable<System.TimeSpan> StartDateTime { get; set; }
        public Nullable<System.TimeSpan> EndDateTime { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Vacancies { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<decimal> MaxPlayers { get; set; }
        public string UserId { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonRegisterEmail> NonRegisterEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
    }
}
