//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAholics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonRegisterEmail
    {
        public int EmailId { get; set; }
        public string Emailaddress { get; set; }
        public Nullable<int> Eventid { get; set; }
        public Nullable<bool> Register { get; set; }
        public string Senderemail { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
