//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAholics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerPreference
    {
        public int PrefferenceID { get; set; }
        public string Name { get; set; }
        public string PreferredRole { get; set; }
        public string PrefferedSport { get; set; }
        public Nullable<System.TimeSpan> PrefferredTimeslotfrom { get; set; }
        public Nullable<System.TimeSpan> PrefferredTimeslotto { get; set; }
        public string PrefferredArea { get; set; }
        public string UserId { get; set; }
    }
}
