//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportAholics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> SportID { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsJoin { get; set; }
        public string EntryUser { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual Event Event { get; set; }
    }
}
